### PR TITLE
Fix setup python

### LINKED ISSUE #22: setup-python
Hi!,

I'm trying to deploy a self-hosted runner and came across this wonderful repo.

Everything worked perfectly -- until I tried using the `setup-python` action.. which fails with the following error:

```
2020-07-30T12:27:36.6953751Z Download action repository 'actions/setup-python@v2'
2020-07-30T12:27:37.6224109Z ##[group]Run actions/setup-python@v2
2020-07-30T12:27:37.6224365Z with:
2020-07-30T12:27:37.6224476Z   python-version: 3.x
2020-07-30T12:27:37.6224747Z   token: ***
2020-07-30T12:27:37.6224852Z env:
2020-07-30T12:27:37.6224951Z   ...
2020-07-30T12:27:37.6225470Z ##[endgroup]
2020-07-30T12:27:37.6554781Z Version 3.x was not found in the local cache
2020-07-30T12:27:38.2418804Z ##[error]Version 3.x with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
2020-07-30T12:27:38.2527363Z Cleaning up orphan processes
```

According to some notes found [here](https://github.com/marketplace/actions/setup-python#linux), I hoped it would be enough to extend the docker image as follows:

```docker
FROM tcardonne/github-runner:latest
ENV AGENT_TOOLSDIRECTORY=/opt/hostedtoolcache
RUN mkdir ${AGENT_TOOLSDIRECTORY}
```

However, still no luck: same error after rebuilding and restarting the docker image.

The above article also mentions that the linux runner can't be started as root. However, it seems that your image uses root, so I assume ownership/permissions shouldn't be the problem here(?).

Do you happen to have any experience with this or related issues?

Best, Thomas

### PR DESCRIPTION
**Pull request by coldfix**
Hi,

this patch allows building an image that supports the `actions/setup-python` action. Images with different base images can be built as follows:

```
docker build -t tcardonne/github-runner:ubuntu-20.04 --build-arg FROM=ubuntu:20.04
docker build -t tcardonne/github-runner:debian-buster --build-arg FROM=debian:buster-slim
...
```

It would be awesome if you could upload a version based on a [supported environment](https://github.com/tcardonne/docker-github-runner) (such as `ubuntu:20.04`)!

Fixes #22

### CODE REVIEW

**Comment by tcardonne** [comment]
Hello,

Thanks for your PR.

As I configured automated builds using Docker Hub, I can't use build arguments and I don't have much time to switch to GitHub Actions (shame!).
Would you mind renaming the `debian-buster/` folder to `docker/` and creating a separate Dockerfile (`Dockerfile.ubuntu-20-04` ?) with the ubuntu FROM ?

With this change I'll be able to create automated builds for `ubuntu:20.04`.

**Comment by coldfix** [comment]
Hi,

thanks for your reply!

> As I configured automated builds using Docker Hub, I can't use build arguments and I don't have much time to switch to GitHub Actions (shame!).

Oh, I see, my experience with Docker Hub is relatively limited apart from uploading one image manually. However, from some google research it seems there is a way to override build arguments using build hooks, see [Advanced options for Autobuild and Autotest](https://docs.docker.com/docker-hub/builds/advanced). I have updated the branch to include such a hook. You would then have to add an autobuild configuration with *Docker Tag* set to `ubuntu-20.04`. The hook will look at the resulting `$IMAGE_NAME`, extract its tag, replace the first dash `-` by a colon `:`, and pass this as `FROM` argument.

> Would you mind renaming the `debian-buster/` folder to `docker/` and creating a separate Dockerfile (`Dockerfile.ubuntu-20-04` ?) with the ubuntu FROM ?

For now, we could avoid the duplicated Dockerfile code by using the hook-based method above. However, this of course only works because the two base images are similar enough; if later on adding base images with more differences that require actual customizations, this may be the most suitable option anyway. Which option do you prefer?

**Comment by coldfix** [comment]
Hi,

just in case this slipped under the radar, do you prefer:

- as is: build hook dispatches different FROM argument for docker hub
- or as you suggested: copy&paste separate Dockerfile for each base image?

Best, Thomas

**Comment by tcardonne** [comment]
Hello,

My apologies for the delay. I created a new release (v1.6.0) with your changes. I fixed the hook to fit the tag scheme (`vX.YZ`).

As stated in the release notes :
> Debian Buster images are tagged with latest and vX.Y.Z and Ubuntu Focal are tagged with ubuntu-20.04 and vX.Y.Z-ubuntu-20.04.

Hope it will fix your initial issue with Python.

Thanks again for your patience and your contribution!

**Comment by coldfix** [comment]
Awesome, thanks!

> I fixed the hook to fit the tag scheme (`vX.YZ`).

Oh, sorry somehow missed that.

**Pull request merged**
